#!/bin/bash

read -p "Log Location: " file

#Verify we can read the file
data=`cat $file`
if [[ "$data" == "" ]]; then
	echo "Unable to read the file path specified"
	echo "Ensure there are no spaces and that the path is correct"
	exit 1
fi

#Check to see what kind of terminal this is to make sure we use the right echo mode, no idea why some are different in this aspect
echotest=`echo -e "test"`
if [[ "$echotest" == "test" ]] ; then
	echomode="-e"
else
	echomode=""
fi


#Impactful PI's new to 10.1 / 10.1.1

# look for PI's 
function PI_005191() {
	eaAttr=$(cat "$file" | grep "ExtensionAttributeMatcherUtils") 
	if [[ $eaAttr != "" ]] ; then
		echo "Look at PI 005191,extension attribute data type and input value mismatch"
		echo "https://na65.salesforce.com/a4g0h000001pIyy?srPos=0&srKp=a4g"
		
	fi	
}


function PI_005168() {
	invalidInt=$(cat "$file" | grep "smartsearch.service.matcher.MobileDeviceDenormalizedDateMatcher.isMatch")
	if [[ $invalidInt != "" ]] ; then
		echo "Look at  PI 005168,upgrade to 10.1+ from 10.0 or below does not check invalid integer data in smart group criteria which will stop mdm functionality"
		echo "https://na65.salesforce.com/a4g0h000001pItA?srPos=0&srKp=a4g"
	
	fi
}
	

function PI_003960() {
	selectCommands=$(cat "$file" | grep "WHERE (apns_result_status='' OR apns_result_status='Error'")
	if [[ $selectCommands != ""]] ; then 
		echo "Look at  PI 003960,Check for pending "InstallApplication" commands for scoped apps after inventory update and MDM installs or updates can cause MySQL bottleneck"
		echo "PI-003960, PI-003783, PI-003112, PI-005048"
		echo "https://na65.salesforce.com/a4g1A000001BFev?srPos=0&srKp=a4g"
		echo "Possible PI 004809"
	
	
}


function 

####################################
PI_005168
PI_005191
PI_003960
